import { IconDefinition } from '@ant-design/icons-angular';
import {
  AimOutline,
  AlertOutline,
  ArrowDownOutline,
  ArrowUpOutline,
  CalendarOutline,
  CheckCircleOutline,
  CheckCircleFill,
  FireOutline,
  PushpinOutline,
  BugOutline,
  BulbOutline,
  ClockCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  CoffeeOutline,
  CompassOutline,
  DeleteOutline,
  DownloadOutline,
  DisconnectOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FallOutline,
  FilterFill,
  FlagOutline,
  FundProjectionScreenOutline,
  GlobalOutline,
  InboxOutline,
  InfoCircleOutline,
  LinkOutline,
  LeftOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MedicineBoxOutline,
  MinusCircleOutline,
  PauseCircleOutline,
  PieChartOutline,
  PlusOutline,
  PoweroffOutline,
  QuestionCircleOutline,
  RightOutline,
  RiseOutline,
  RollbackOutline,
  RocketOutline,
  SafetyCertificateOutline,
  SafetyOutline,
  ReloadOutline,
  SearchOutline,
  SettingOutline,
  ShareAltOutline,
  StarFill,
  StepBackwardOutline,
  StepForwardOutline,
  StopOutline,
  SwapOutline,
  BranchesOutline,
  ColumnHeightOutline,
  WarningOutline,
  TableOutline,
  TeamOutline,
  UserAddOutline,
  ThunderboltOutline,
  ToolOutline,
  TrophyOutline,
  UpOutline,
  DownOutline,
  UnorderedListOutline,
  WifiOutline,
} from '@ant-design/icons-angular/icons';

/** The icons the app registers, in one place: `provideNzIcons(NZ_ICONS)` in app.config.ts
 *  reads it, and so must any TestBed that renders a component containing an `<nz-icon>`
 *  (otherwise the icon is fetched dynamically, 404s, and the test hangs). */
export const NZ_ICONS: IconDefinition[] = [
  // Scarica rose e scelte dal Draft Assistant (29/09/2026): non e' nella lista di default di ng-zorro.
  DownloadOutline,
  // LE DUE FRECCE DEL VERSO D'ORDINAMENTO (Strategia, 16/09/2026). Registrate perche' la lista
  // di default di ng-zorro non le contiene: un'icona non registrata disegna una casella vuota e la
  // pagina urla «<svg> tag not found» in console, che e' il difetto gia' pagato il 13/09 su `user-add`.
  ArrowDownOutline,
  ArrowUpOutline,
  AimOutline,
  AlertOutline,
  CalendarOutline,
  CheckCircleOutline,
  CheckCircleFill,
  FireOutline,
  PushpinOutline,
  BugOutline,
  BulbOutline,
  ClockCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  CoffeeOutline,
  CompassOutline,
  DeleteOutline,
  DisconnectOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FallOutline,
  FilterFill,
  FlagOutline,
  FundProjectionScreenOutline,
  GlobalOutline,
  InboxOutline,
  InfoCircleOutline,
  LinkOutline,
  // LA FRECCIA CHE PIEGA un blocco della Strategia (23/09/2026). `right` c'era gia' e `left` no,
  // e le due sono i due versi dello stesso gesto: registrarne una sola avrebbe lasciato una
  // casella vuota su meta degli stati.
  LeftOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MedicineBoxOutline,
  MinusCircleOutline,
  PauseCircleOutline,
  PieChartOutline,
  PlusOutline,
  PoweroffOutline,
  QuestionCircleOutline,
  RightOutline,
  RiseOutline,
  RollbackOutline,
  RocketOutline,
  SafetyCertificateOutline,
  SafetyOutline,
  ReloadOutline,
  SearchOutline,
  SettingOutline,
  ShareAltOutline,
  StarFill,
  // INIZIO E FINE della revisione di un draft (30/09/2026): non sono nella lista di default di ng-zorro.
  StepBackwardOutline,
  StepForwardOutline,
  StopOutline,
  SwapOutline,
  BranchesOutline,
  ColumnHeightOutline,
  WarningOutline,
  TableOutline,
  TeamOutline,
  UserAddOutline,
  ThunderboltOutline,
  ToolOutline,
  TrophyOutline,
  UpOutline,
  DownOutline,
  UnorderedListOutline,
  WifiOutline,
];
